[tool.poetry]
name = "learn-python-2025-bot"
version = "0.1.0"
description = ""
authors = ["Alex_K <skiselev94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
